name: Auto-merge Dependabot

on:
  # Use pull_request_target to ensure the workflow runs in the context of the base repo
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, edited, dismissed]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  automerge:
    # Only act on Dependabot PRs/events
    if: >-
      ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable GitHub auto-merge (patch/minor)
        if: >-
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
        continue-on-error: true
